// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef about_panel_h
#define about_panel_h
#include <fltk/DoubleBufferWindow.h>
extern gnui::DoubleBufferWindow* about_panel;
#include <fltk/Group.h>
extern gnui::Group* display_group;
#include <fltk/ReturnButton.h>
extern gnui::ReturnButton* about_ok;
gnui::DoubleBufferWindow* make_about_panel(const char *copyright);
#endif
