// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef CubeViewUI_h
#define CubeViewUI_h
#include <fltk/Window.h>
#include <fltk/Group.h>
#include <fltk/ValueSlider.h>
#include <fltk/ThumbWheel.h>
#include <stdio.h>
#include <fltk/Slider.h>
#include <fltk/InvisibleBox.h>
#include "CubeView.h"

class CubeViewUI  {
public:
  CubeViewUI();
private:
  gnui::Window *mainWindow;
public:
      gnui::ValueSlider *zoom;
private:
      inline void cb_zoom_i(gnui::ValueSlider*, void*);
      static void cb_zoom(gnui::ValueSlider*, void*);
public:
      gnui::Group *VChange;
        gnui::ThumbWheel *vrot;
private:
        inline void cb_vrot_i(gnui::ThumbWheel*, void*);
        static void cb_vrot(gnui::ThumbWheel*, void*);
public:
        gnui::Slider *ypan;
private:
        inline void cb_ypan_i(gnui::Slider*, void*);
        static void cb_ypan(gnui::Slider*, void*);
public:
      gnui::Group *HChange;
        gnui::Slider *xpan;
private:
        inline void cb_xpan_i(gnui::Slider*, void*);
        static void cb_xpan(gnui::Slider*, void*);
public:
        gnui::ThumbWheel *hrot;
private:
        inline void cb_hrot_i(gnui::ThumbWheel*, void*);
        static void cb_hrot(gnui::ThumbWheel*, void*);
public:
      gnui::Group *MainView;
        gnui::InvisibleBox *cframe;
        CubeView *cube;
  void show();
};
#endif
