// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef fast_slow_h
#define fast_slow_h
#include <FL/Fl.H>
#include <FL/GNUI_Window.H>
#include <FL/GNUI_Slider.H>
extern GNUI_Slider* control;
extern GNUI_Slider* fast;
extern GNUI_Slider* slow;
#include <FL/GNUI_Box.H>
#endif
