// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef image_file_h
#define image_file_h
#include <fltk/Fl.h>
#include <fltk/GNUI_Window.h>
extern GNUI_Window* window;
#include <fltk/GNUI_Box.h>
#include <fltk/GNUI_Value_Slider.h>
extern GNUI_Value_Slider* slider;
#include <fltk/GNUI_Button.h>
#include <fltk/GNUI_Bitmap.h>
extern GNUI_Window* browser_window;
#include <fltk/GNUI_Browser.h>
extern GNUI_Browser* browser;
extern GNUI_Window* image_window;
extern GNUI_Box* image_box;
#endif
