// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "keyboard_ui.h"
#include <fltk/events.h>

gnui::Output *key_output=(gnui::Output *)0;

gnui::Output *text_output=(gnui::Output *)0;

gnui::Window* make_window() {
  gnui::Window* w;
   {gnui::Window* o = new gnui::Window(490, 190);
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::Output* o = key_output = new gnui::Output(15, 15, 170, 30, "gnui::event_key():");
      o->textfont(gnui::COURIER);
      o->labelsize(10);
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
    }
     {gnui::Output* o = text_output = new gnui::Output(195, 15, 190, 30, "gnui::event_text():");
      o->textfont(gnui::COURIER);
      o->labelsize(10);
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
    }
     {gnui::Button* o = new gnui::Button(15, 50, 20, 20, "Esc ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::EscapeKey));
    }
     {gnui::Button* o = new gnui::Button(50, 50, 20, 20, "F1");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F1Key));
    }
     {gnui::Button* o = new gnui::Button(70, 50, 20, 20, "F2");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F2Key));
    }
     {gnui::Button* o = new gnui::Button(90, 50, 20, 20, "F3");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F3Key));
    }
     {gnui::Button* o = new gnui::Button(110, 50, 20, 20, "F4");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F4Key));
    }
     {gnui::Button* o = new gnui::Button(140, 50, 20, 20, "F5");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F5Key));
    }
     {gnui::Button* o = new gnui::Button(160, 50, 20, 20, "F6");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F6Key));
    }
     {gnui::Button* o = new gnui::Button(180, 50, 20, 20, "F7");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F7Key));
    }
     {gnui::Button* o = new gnui::Button(200, 50, 20, 20, "F8");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F8Key));
    }
     {gnui::Button* o = new gnui::Button(230, 50, 20, 20, "F9");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F9Key));
    }
     {gnui::Button* o = new gnui::Button(250, 50, 20, 20, "F10");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F10Key));
    }
     {gnui::Button* o = new gnui::Button(270, 50, 20, 20, "F11");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F11Key));
    }
     {gnui::Button* o = new gnui::Button(290, 50, 20, 20, "F12");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::F12Key));
    }
     {gnui::Button* o = new gnui::Button(325, 50, 20, 20, "Print ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::PrintKey));
    }
     {gnui::Button* o = new gnui::Button(345, 50, 20, 20, "Sclk ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::ScrollLockKey));
    }
     {gnui::Button* o = new gnui::Button(365, 50, 20, 20, "Paus ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::PauseKey));
    }
     {gnui::Button* o = new gnui::Button(15, 80, 20, 20, "`");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(35, 80, 20, 20, "1");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(55, 80, 20, 20, "2");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(75, 80, 20, 20, "3");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(95, 80, 20, 20, "4");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(115, 80, 20, 20, "5");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(135, 80, 20, 20, "6");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(155, 80, 20, 20, "7");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(175, 80, 20, 20, "8");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(195, 80, 20, 20, "9");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(215, 80, 20, 20, "0");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(235, 80, 20, 20, "-");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(255, 80, 20, 20, "=");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(275, 80, 35, 20, "Bksp");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::BackSpaceKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(325, 80, 20, 20, "Ins ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::InsertKey));
    }
     {gnui::Button* o = new gnui::Button(345, 80, 20, 20, "Home");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::HomeKey));
    }
     {gnui::Button* o = new gnui::Button(365, 80, 20, 20, "pgup ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::PageUpKey));
    }
     {gnui::Button* o = new gnui::Button(400, 80, 20, 20, "Num");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::NumLockKey));
    }
     {gnui::Button* o = new gnui::Button(420, 80, 20, 20, "/");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'/'));
    }
     {gnui::Button* o = new gnui::Button(440, 80, 20, 20, "*");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'*'));
    }
     {gnui::Button* o = new gnui::Button(460, 80, 20, 20, "-");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'-'));
    }
     {gnui::Button* o = new gnui::Button(15, 100, 27, 20, "Tab");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::TabKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(42, 100, 20, 20, "Q");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(62, 100, 20, 20, "W");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(82, 100, 20, 20, "E");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(102, 100, 20, 20, "R");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(122, 100, 20, 20, "T");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(142, 100, 20, 20, "Y");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(162, 100, 20, 20, "U");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(182, 100, 20, 20, "I");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(202, 100, 20, 20, "O");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(222, 100, 20, 20, "P");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(242, 100, 20, 20, "[");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(262, 100, 20, 20, "]");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(282, 100, 28, 20, "\\");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(325, 100, 20, 20, "Del ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::DeleteKey));
    }
     {gnui::Button* o = new gnui::Button(345, 100, 20, 20, "End ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::EndKey));
    }
     {gnui::Button* o = new gnui::Button(365, 100, 20, 20, "pgdn ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::PageDownKey));
    }
     {gnui::Button* o = new gnui::Button(400, 100, 20, 20, "7");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'7'));
    }
     {gnui::Button* o = new gnui::Button(420, 100, 20, 20, "8");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'8'));
    }
     {gnui::Button* o = new gnui::Button(440, 100, 20, 20, "9");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'9'));
    }
     {gnui::Button* o = new gnui::Button(460, 100, 20, 40, "+");
      o->set_vertical();
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'+'));
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(15, 120, 36, 20, "Lock");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::CapsLockKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(51, 120, 20, 20, "A");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(71, 120, 20, 20, "S");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(91, 120, 20, 20, "D");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(111, 120, 20, 20, "F");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(131, 120, 20, 20, "G");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(151, 120, 20, 20, "H");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(171, 120, 20, 20, "J");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(191, 120, 20, 20, "K");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(211, 120, 20, 20, "L");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(231, 120, 20, 20, ";");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(251, 120, 20, 20, "'");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(271, 120, 39, 20, "Enter");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::ReturnKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(400, 120, 20, 20, "4");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'4'));
    }
     {gnui::Button* o = new gnui::Button(420, 120, 20, 20, "5");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'5'));
    }
     {gnui::Button* o = new gnui::Button(440, 120, 20, 20, "6");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'6'));
    }
     {gnui::Button* o = new gnui::Button(15, 140, 45, 20, "Shift");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::LeftShiftKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(60, 140, 20, 20, "Z");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(80, 140, 20, 20, "X");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(100, 140, 20, 20, "C");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(120, 140, 20, 20, "V");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(140, 140, 20, 20, "B");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(160, 140, 20, 20, "N");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(180, 140, 20, 20, "M");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(200, 140, 20, 20, ",");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(220, 140, 20, 20, ".");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(240, 140, 20, 20, "/");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb);
    }
     {gnui::Button* o = new gnui::Button(260, 140, 50, 20, "Shift");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::RightShiftKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(345, 140, 20, 20, "@8->");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::UpKey));
    }
     {gnui::Button* o = new gnui::Button(400, 140, 20, 20, "1");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'1'));
    }
     {gnui::Button* o = new gnui::Button(420, 140, 20, 20, "2");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'2'));
    }
     {gnui::Button* o = new gnui::Button(440, 140, 20, 20, "3");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'3'));
    }
     {gnui::Button* o = new gnui::Button(460, 140, 20, 40);
      o->set_vertical();
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::KeypadEnter));
    }
     {gnui::Button* o = new gnui::Button(15, 160, 30, 20, "Ctrl");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::LeftCtrlKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(45, 160, 30, 20, "Meta");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::LeftMetaKey));
    }
     {gnui::Button* o = new gnui::Button(75, 160, 30, 20, "Alt ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::LeftAltKey));
    }
     {gnui::Button* o = new gnui::Button(105, 160, 85, 20);
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(' '));
    }
     {gnui::Button* o = new gnui::Button(190, 160, 30, 20, "Alt ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::RightAltKey));
    }
     {gnui::Button* o = new gnui::Button(220, 160, 30, 20, "Meta");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::RightMetaKey));
    }
     {gnui::Button* o = new gnui::Button(250, 160, 30, 20, "Menu ");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::MenuKey));
    }
     {gnui::Button* o = new gnui::Button(280, 160, 30, 20, "Ctrl");
      o->labelsize(8);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::RightCtrlKey));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(325, 160, 20, 20, "@4->");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::LeftKey));
    }
     {gnui::Button* o = new gnui::Button(345, 160, 20, 20, "@2->");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::DownKey));
    }
     {gnui::Button* o = new gnui::Button(365, 160, 20, 20, "@6->");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::RightKey));
    }
     {gnui::Button* o = new gnui::Button(400, 160, 40, 20, "0");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'0'));
      o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
    }
     {gnui::Button* o = new gnui::Button(440, 160, 20, 20, ".");
      o->labelsize(10);
      o->callback((gnui::Callback*)key_cb, (void*)(gnui::Keypad+'.'));
    }
     {gnui::Widget* o = new gnui::Widget(400, 15, 80, 40, "gnui::event_state():");
      o->box(gnui::NO_BOX);
      o->labelsize(10);
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
    }
     {gnui::Button* o = new gnui::Button(400, 15, 20, 10, "shift ");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::SHIFT));
    }
     {gnui::Button* o = new gnui::Button(420, 15, 20, 10, "lock ");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::CAPSLOCK));
    }
     {gnui::Button* o = new gnui::Button(440, 15, 20, 10, "ctrl");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::CTRL));
    }
     {gnui::Button* o = new gnui::Button(460, 15, 20, 10, "alt");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::ALT));
    }
     {gnui::Button* o = new gnui::Button(400, 25, 20, 10, "num");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::NUMLOCK));
    }
     {gnui::Button* o = new gnui::Button(420, 25, 20, 10, "?");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(0x20));
    }
     {gnui::Button* o = new gnui::Button(440, 25, 20, 10, "meta");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::META));
    }
     {gnui::Button* o = new gnui::Button(460, 25, 20, 10, "sclk");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::SCROLLLOCK));
    }
     {gnui::Button* o = new gnui::Button(400, 35, 20, 10, "b1");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::BUTTON1));
    }
     {gnui::Button* o = new gnui::Button(420, 35, 20, 10, "b2");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::BUTTON2));
    }
     {gnui::Button* o = new gnui::Button(440, 35, 20, 10, "b3");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(gnui::BUTTON3));
    }
     {gnui::Button* o = new gnui::Button(460, 35, 20, 10, "?");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(0x800));
    }
     {gnui::Button* o = new gnui::Button(400, 45, 20, 10, "?");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(0x1000));
    }
     {gnui::Button* o = new gnui::Button(420, 45, 20, 10, "?");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(0x2000));
    }
     {gnui::Button* o = new gnui::Button(440, 45, 20, 10, "?");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(0x4000));
    }
     {gnui::Button* o = new gnui::Button(460, 45, 20, 10, "?");
      o->selection_color((gnui::Color)3);
      o->labelsize(8);
      o->callback((gnui::Callback*)shift_cb, (void*)(0x8000));
    }
    o->end();
    o->shortcut(0);
    o->resizable(o);
  }
  return  w;
}
