// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "tabs.h"

gnui::Window *foo_window=(gnui::Window *)0;

static void cb_cancel(gnui::Button*, void*) {
  exit(1);
}

static void cb_OK(gnui::ReturnButton*, void*) {
  exit(0);
}

#include <fltk/run.h>

int main (int argc, char **argv) {

  gnui::Window* w;
   {gnui::Window* o = foo_window = new gnui::Window(320, 296);
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::TabGroup* o = new gnui::TabGroup(10, 10, 300, 191);
      o->begin();
       {gnui::Group* o = new gnui::Group(0, 20, 300, 171, "Label1");
        o->begin();
        new gnui::Input(50, 14, 240, 22, "input:");
        new gnui::Input(50, 36, 240, 22, "input2:");
         {gnui::WordwrapInput* o = new gnui::WordwrapInput(50, 58, 240, 99, "input3:");
          o->type(5);
        }
        o->end();
        gnui::Group::current()->resizable(o);
      }
       {gnui::Group* o = new gnui::Group(0, 20, 300, 171, "tab2");
        o->hide();
        o->begin();
        new gnui::Button(10, 25, 100, 22, "button1");
        new gnui::Input(130, 58, 100, 22, "input in box2");
        new gnui::Button(20, 113, 260, 22, "This is stuff inside the Fl_Group \"tab2\"");
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 20, 300, 171, "tab3");
        o->hide();
        o->begin();
         {gnui::Button* o = new gnui::Button(10, 30, 60, 80, "button2");
          o->set_vertical();
        }
         {gnui::Button* o = new gnui::Button(70, 30, 60, 80, "button");
          o->set_vertical();
        }
         {gnui::Button* o = new gnui::Button(130, 30, 60, 80, "button");
          o->set_vertical();
        }
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 20, 300, 171, "tab4");
        o->labelfont(gnui::HELVETICA_ITALIC);
        o->hide();
        o->begin();
         {gnui::Button* o = new gnui::Button(10, 20, 60, 110, "button2");
          o->set_vertical();
        }
         {gnui::Button* o = new gnui::Button(70, 20, 60, 110, "button");
          o->set_vertical();
        }
         {gnui::Button* o = new gnui::Button(130, 20, 60, 110, "button");
          o->set_vertical();
        }
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 20, 300, 171, "very long tab text");
        o->labeltype(gnui::ENGRAVED_LABEL);
        o->hide();
        o->begin();
         {gnui::Button* o = new gnui::Button(10, 50, 60, 80, "button2");
          o->set_vertical();
        }
         {gnui::Button* o = new gnui::Button(80, 60, 60, 80, "button");
          o->set_vertical();
        }
         {gnui::Clock* o = new gnui::Clock(155, 13, 100, 100, "Make sure this clock does not use processor time when this tab is hidden or w\
indow is iconized");
          o->box(gnui::OSHADOW_BOX);
          o->labelfont(gnui::TIMES);
          o->color((gnui::Color)238);
          o->labelsize(10);
          o->align(gnui::ALIGN_BOTTOM|gnui::ALIGN_WRAP);
        }
        o->end();
      }
      o->end();
      gnui::Group::current()->resizable(o);
    }
    new gnui::Input(60, 211, 130, 22, "inputA:");
    new gnui::Input(60, 233, 250, 22, "inputB:");
     {gnui::Button* o = new gnui::Button(180, 266, 60, 22, "cancel");
      o->callback((gnui::Callback*)cb_cancel);
    }
     {gnui::ReturnButton* o = new gnui::ReturnButton(250, 266, 60, 22, "OK");
      o->shortcut(0xff0d);
      o->callback((gnui::Callback*)cb_OK);
    }
    o->end();
  }
  w->show(argc, argv);
  return  gnui::run();
}
