// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef valuators_h
#define valuators_h
#include <fltk/Window.h>
#include <stdio.h>
#include <fltk/Widget.h>
#include <fltk/Slider.h>
extern void callback(gnui::Slider*, void*);
#include <fltk/ValueInput.h>
extern void callback(gnui::ValueInput*, void*);
#include <fltk/Scrollbar.h>
extern void callback(gnui::Scrollbar*, void*);
#include <fltk/ValueSlider.h>
extern void callback(gnui::ValueSlider*, void*);
#include <fltk/ThumbWheel.h>
extern void callback(gnui::ThumbWheel*, void*);
#include <fltk/Group.h>
#include <fltk/Dial.h>
extern void callback(gnui::Dial*, void*);
#endif
