// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef HelpDialog_h
#define HelpDialog_h
// Header for //\n// "$Id: HelpDialog.fl 4721 2005-12-19 16:52:...
#include <gnui/DoubleBufferWindow.h>
#include <gnui/HelpView.h>
#include <gnui/Group.h>
#include <gnui/Button.h>
#include <gnui/Input.h>

namespace gnui  {

class GNUI_IMAGES_API HelpDialog  {
  int index_;
  int max_;
  int line_[100];
  char file_[100][256];
  int find_pos_;
public:
  HelpDialog();
private:
  gnui::DoubleBufferWindow *window_;
    gnui::HelpView *view_;
    inline void cb_view__i(gnui::HelpView*, void*);
    static void cb_view_(gnui::HelpView*, void*);
      inline void cb_Close_i(gnui::Button*, void*);
      static void cb_Close(gnui::Button*, void*);
      gnui::Button *back_;
      inline void cb_back__i(gnui::Button*, void*);
      static void cb_back_(gnui::Button*, void*);
      gnui::Button *forward_;
      inline void cb_forward__i(gnui::Button*, void*);
      static void cb_forward_(gnui::Button*, void*);
      gnui::Button *smaller_;
      inline void cb_smaller__i(gnui::Button*, void*);
      static void cb_smaller_(gnui::Button*, void*);
      gnui::Button *larger_;
      inline void cb_larger__i(gnui::Button*, void*);
      static void cb_larger_(gnui::Button*, void*);
        gnui::Input *find_;
        inline void cb_find__i(gnui::Input*, void*);
        static void cb_find_(gnui::Input*, void*);
public:
  ~HelpDialog();
  int h();
  void hide();
  void load(const char *f);
  void position(int xx, int yy);
  void resize(int xx, int yy, int ww, int hh);
  void show();
  void show(int argc, char **argv);
  void textsize(uchar s);
  uchar textsize();
  void topline(const char *n);
  void topline(int n);
  void value(const char *f);
  const char * value() const;
  int visible();
  int w();
  int x();
  int y();
};
}
// Header for //\n// End of "$Id: HelpDialog.fl 4721 2005-12-19...
#endif
