// generated by Fast Light User Interface Designer (fluid) version 2.0000

#ifndef essai_panel_h
#define essai_panel_h
#include <FL/Fl.H>
extern GNUI_Group *Essai;
#include <FL/GNUI_Slider.H>
extern void major_tick_precision_cb(GNUI_Slider*, void*);
GNUI_Group* make_window();
#endif
