// generated by Fast Light User Interface Designer (fluid) version 2.0000

#include "essai_panel.h"

GNUI_Group *Essai=(GNUI_Group *)0;

GNUI_Group* make_window() {
  GNUI_Group* w;
  { GNUI_Group* o = Essai = new GNUI_Group(0, 0, 258, 74);
    w = o;
    { GNUI_Slider* o = new GNUI_Slider(20, 20, 225, 20, "Major tick precision");
      o->type(5);
      o->maximum(6);
      o->step(1);
      o->callback((GNUI_Callback*)major_tick_precision_cb);
    }
    o->end();
  }
  return w;
}
