// generated by Fast Light User Interface Designer (gnuid) version 2.0100

#ifndef about_panel_h
#define about_panel_h
#include <gnui/DoubleBufferWindow.h>
extern gnui::DoubleBufferWindow* about_panel;
#include <gnui/Group.h>
extern gnui::Group* display_group;
#include <gnui/ReturnButton.h>
extern gnui::ReturnButton* about_ok;
gnui::DoubleBufferWindow* make_about_panel(const char *copyright);
#endif
