// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#include "alignment_panel.h"
#include "PrefsData.h"
#include "FluidType.h"
gnui::TextBuffer *shell_run_buffer;

gnui::Window *preferences_window=(gnui::Window *)0;

gnui::TabGroup *pref_tabs=(gnui::TabGroup *)0;

static void cb_pref_tabs(gnui::TabGroup*, void*) {
  initialize_tab_colors();
}

gnui::CheckButton *openlast_button=(gnui::CheckButton *)0;

static void cb_openlast_button(gnui::CheckButton*, void*) {
  prefs.open_previous_file(openlast_button->value());
}

gnui::CheckButton *prevpos_button=(gnui::CheckButton *)0;

static void cb_prevpos_button(gnui::CheckButton*, void*) {
  prefs.prev_window_pos(prevpos_button->value());
}

gnui::CheckButton *completion_button=(gnui::CheckButton *)0;

static void cb_completion_button(gnui::CheckButton*, void*) {
  prefs.show_completion_dialogs(completion_button->value());
}

gnui::ValueInput *recent_spinner=(gnui::ValueInput *)0;

static void cb_recent_spinner(gnui::ValueInput*, void*) {
  prefs.recent_files((int) recent_spinner->value()); load_history();
}

gnui::CheckButton *tabcolor_button=(gnui::CheckButton *)0;

static void cb_tabcolor_button(gnui::CheckButton* o, void*) {
  prefs.tabcolor(o->value());
  initialize_tab_colors();
}

gnui::CheckButton *splash_button=(gnui::CheckButton *)0;

static void cb_splash_button(gnui::CheckButton* o, void*) {
  prefs.show_splash(o->value());
}

gnui::Input *header_file_input=(gnui::Input *)0;

gnui::Input *code_file_input=(gnui::Input *)0;

gnui::CheckButton *include_H_from_C_button=(gnui::CheckButton *)0;

gnui::Input *horizontal_input=(gnui::Input *)0;

gnui::Input *vertical_input=(gnui::Input *)0;

gnui::Input *snap_input=(gnui::Input *)0;

gnui::RadioButton *def_widget_size[6]={(gnui::RadioButton *)0};

static void cb_Close(gnui::Button*, void*) {
  preferences_window->hide();
}

gnui::Window* make_preferences_window() {
  gnui::Window* w;
   {gnui::Window* o = preferences_window = new gnui::Window(370, 253, "gnuid Preferences");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::TabGroup* o = pref_tabs = new gnui::TabGroup(5, 4, 360, 210);
      o->callback((gnui::Callback*)cb_pref_tabs);
      o->begin();
       {gnui::Group* o = new gnui::Group(0, 21, 360, 188, "General");
        o->color((gnui::Color)0x54c2d400);
        o->begin();
         {gnui::CheckButton* o = openlast_button = new gnui::CheckButton(10, 5, 190, 25, "Open Previous File on Startup");
          o->callback((gnui::Callback*)cb_openlast_button);
          openlast_button->value(prefs.open_previous_file() ? true : false);
        }
         {gnui::CheckButton* o = prevpos_button = new gnui::CheckButton(10, 25, 190, 25, "Remember Window Positions");
          o->callback((gnui::Callback*)cb_prevpos_button);
          prevpos_button->value(prefs.prev_window_pos() ? true : false);
        }
         {gnui::CheckButton* o = completion_button = new gnui::CheckButton(10, 45, 186, 25, "Show Completion Dialog Info");
          o->callback((gnui::Callback*)cb_completion_button);
          completion_button->value(prefs.show_completion_dialogs() ? true : false);
        }
         {gnui::ValueInput* o = recent_spinner = new gnui::ValueInput(13, 93, 37, 25, "# Recent Files");
          o->callback((gnui::Callback*)cb_recent_spinner);
          o->align(gnui::ALIGN_RIGHT);
          o->when(gnui::WHEN_CHANGED);
          recent_spinner->maximum(10); recent_spinner->value(prefs.recent_files());
        }
         {gnui::CheckButton* o = tabcolor_button = new gnui::CheckButton(10, 125, 100, 25, "Colorful tabs");
          o->callback((gnui::Callback*)cb_tabcolor_button);
          o->value(prefs.tabcolor() ? true : false);
        }
         {gnui::CheckButton* o = splash_button = new gnui::CheckButton(10, 65, 190, 25, "Show splash screen on startup");
          o->callback((gnui::Callback*)cb_splash_button);
          o->value(prefs.show_splash() ? true : false);
        }
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 20, 360, 190, "Code generation");
        o->color((gnui::Color)0x13d47a00);
        o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
        o->hide();
        o->begin();
         {gnui::Widget* o = new gnui::Widget(16, 0, 323, 25, "Use \"name.ext\" to set name or just \".ext\" to set only extension.");
          o->box(gnui::NO_BOX);
          o->labelsize(11);
          o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE|gnui::ALIGN_WRAP);
        }
         {gnui::Input* o = header_file_input = new gnui::Input(96, 30, 185, 22, "Header File:");
          o->callback((gnui::Callback*)header_input_cb, (void*)(1));
          o->when(gnui::WHEN_CHANGED);
        }
         {gnui::Input* o = code_file_input = new gnui::Input(96, 57, 185, 22, "Code File:");
          o->callback((gnui::Callback*)code_input_cb, (void*)(1));
          o->when(gnui::WHEN_CHANGED);
        }
         {gnui::CheckButton* o = include_H_from_C_button = new gnui::CheckButton(16, 84, 170, 22, "#include \"header\" in code");
          o->set_flag(gnui::STATE);
          o->callback((gnui::Callback*)include_H_from_C_button_cb);
        }
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 21, 360, 189, "Alignment");
        o->color((gnui::Color)0xd49a5600);
        o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
        o->hide();
        o->begin();
         {gnui::Input* o = horizontal_input = new gnui::Input(75, 6, 100, 22, "Horizontal:");
          o->labelsize(14);
          o->textsize(14);
          o->callback((gnui::Callback*)alignment_cb, (void*)(1));
          o->when(gnui::WHEN_RELEASE|gnui::WHEN_ENTER_KEY);
        }
         {gnui::Input* o = vertical_input = new gnui::Input(238, 6, 100, 22, "Vertical:");
          o->labelsize(14);
          o->textsize(14);
          o->callback((gnui::Callback*)alignment_cb, (void*)(2));
          o->when(gnui::WHEN_RELEASE|gnui::WHEN_ENTER_KEY);
        }
         {gnui::Input* o = snap_input = new gnui::Input(75, 40, 100, 22, "Snap:");
          o->labelsize(14);
          o->textsize(14);
          o->callback((gnui::Callback*)alignment_cb, (void*)(3));
          o->when(gnui::WHEN_RELEASE|gnui::WHEN_ENTER_KEY);
        }
         {gnui::Group* o = new gnui::Group(73, 75, 207, 85, "Widget\n Size:");
          o->align(gnui::ALIGN_LEFT);
          o->begin();
           {gnui::RadioButton* o = def_widget_size[0] = new gnui::RadioButton(0, 0, 83, 25, "Tiny");
            o->labelsize(8);
            o->callback((gnui::Callback*)default_widget_size_cb, (void*)(8));
            o->align(gnui::ALIGN_LEFT|gnui::ALIGN_RIGHT|gnui::ALIGN_INSIDE);
          }
           {gnui::RadioButton* o = def_widget_size[1] = new gnui::RadioButton(100, 0, 70, 25, "Small");
            o->labelsize(11);
            o->callback((gnui::Callback*)default_widget_size_cb, (void*)(11));
          }
           {gnui::RadioButton* o = def_widget_size[2] = new gnui::RadioButton(0, 25, 83, 25, "Normal");
            o->callback((gnui::Callback*)default_widget_size_cb, (void*)(14));
            o->align(gnui::ALIGN_LEFT|gnui::ALIGN_RIGHT|gnui::ALIGN_INSIDE);
          }
           {gnui::RadioButton* o = def_widget_size[3] = new gnui::RadioButton(100, 25, 90, 25, "medium");
            o->labelsize(18);
            o->callback((gnui::Callback*)default_widget_size_cb, (void*)(18));
          }
           {gnui::RadioButton* o = def_widget_size[4] = new gnui::RadioButton(0, 50, 83, 26, "large");
            o->labelsize(24);
            o->callback((gnui::Callback*)default_widget_size_cb, (void*)(24));
            o->align(gnui::ALIGN_LEFT|gnui::ALIGN_RIGHT|gnui::ALIGN_INSIDE);
          }
           {gnui::RadioButton* o = def_widget_size[5] = new gnui::RadioButton(100, 50, 95, 25, "huge");
            o->labelsize(32);
            o->callback((gnui::Callback*)default_widget_size_cb, (void*)(32));
          }
          o->end();
        }
        o->end();
      }
      o->end();
    }
     {gnui::Button* o = new gnui::Button(139, 222, 106, 25, "Close");
      o->callback((gnui::Callback*)cb_Close);
    }
    o->end();
    o->set_non_modal();
    o->resizable(o);
  }
  return  w;
}

gnui::DoubleBufferWindow *shell_window=(gnui::DoubleBufferWindow *)0;

gnui::Input *shell_command_input=(gnui::Input *)0;

static void cb_shell_command_input(gnui::Input*, void*) {
  prefs.shell_command(shell_command_input->value());
}

gnui::CheckButton *shell_writecode_button=(gnui::CheckButton *)0;

static void cb_shell_writecode_button(gnui::CheckButton*, void*) {
  prefs.shell_writecode(shell_writecode_button->value());
}

gnui::CheckButton *shell_writemsgs_button=(gnui::CheckButton *)0;

static void cb_shell_writemsgs_button(gnui::CheckButton*, void*) {
  prefs.shell_writemsgs(shell_writemsgs_button->value());
}

gnui::CheckButton *shell_savegnui_button=(gnui::CheckButton *)0;

static void cb_shell_savegnui_button(gnui::CheckButton*, void*) {
  prefs.shell_savegnui(shell_savegnui_button->value());
}

static void cb_Cancel(gnui::Button*, void*) {
  shell_window->hide();
}

gnui::DoubleBufferWindow *shell_run_window=(gnui::DoubleBufferWindow *)0;

gnui::TextDisplay *shell_run_display=(gnui::TextDisplay *)0;

gnui::ReturnButton *shell_run_button=(gnui::ReturnButton *)0;

static void cb_shell_run_button(gnui::ReturnButton*, void*) {
  shell_run_window->hide();
}

gnui::DoubleBufferWindow* make_shell_window() {
  gnui::DoubleBufferWindow* w;
   {gnui::DoubleBufferWindow* o = shell_window = new gnui::DoubleBufferWindow(365, 125, "Shell Command");
    o->type(241);
    o->shortcut(0xff1b);
    o->begin();
     {gnui::Input* o = shell_command_input = new gnui::Input(10, 27, 347, 25, "Command:");
      o->labelfont(gnui::HELVETICA_BOLD);
      o->callback((gnui::Callback*)cb_shell_command_input);
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      shell_command_input->value(prefs.shell_command());
    }
     {gnui::CheckButton* o = shell_writecode_button = new gnui::CheckButton(127, 61, 93, 19, "Write Code");
      o->callback((gnui::Callback*)cb_shell_writecode_button);
      shell_writecode_button->value(prefs.shell_writecode() ? true : false);
    }
     {gnui::CheckButton* o = shell_writemsgs_button = new gnui::CheckButton(231, 61, 126, 19, "Write Messages");
      o->callback((gnui::Callback*)cb_shell_writemsgs_button);
      o->hide();
      shell_writemsgs_button->value(prefs.shell_writemsgs() ? true : false);
    }
     {gnui::CheckButton* o = shell_savegnui_button = new gnui::CheckButton(10, 61, 108, 19, "Save Fluid File");
      o->callback((gnui::Callback*)cb_shell_savegnui_button);
      shell_savegnui_button->value(prefs.shell_savegnui() ? true : false);
    }
     {gnui::ReturnButton* o = new gnui::ReturnButton(132, 90, 143, 25, "Run Command");
      o->shortcut(0xff0d);
      o->callback((gnui::Callback*)do_shell_command);
    }
     {gnui::Button* o = new gnui::Button(285, 90, 72, 25, "Cancel");
      o->callback((gnui::Callback*)cb_Cancel);
    }
    o->end();
    o->resizable(o);
  }
   {gnui::DoubleBufferWindow* o = shell_run_window = new gnui::DoubleBufferWindow(555, 430, "Shell Command Output");
    w = o;
    o->type(241);
    o->shortcut(0xff1b);
    o->begin();
     {gnui::TextDisplay* o = shell_run_display = new gnui::TextDisplay(10, 10, 535, 375);
      o->textfont(gnui::COURIER);
      shell_run_buffer = new gnui::TextBuffer();
      shell_run_display->buffer(shell_run_buffer);
    }
     {gnui::ReturnButton* o = shell_run_button = new gnui::ReturnButton(468, 395, 77, 25, "Close");
      o->shortcut(0xff0d);
      o->callback((gnui::Callback*)cb_shell_run_button);
    }
    o->end();
    o->resizable(o);
  }
  return  w;
}
