// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#include "function_panel.h"

gnui::Window *function_panel=(gnui::Window *)0;

gnui::CheckButton *f_public_button=(gnui::CheckButton *)0;

gnui::CheckButton *f_c_button=(gnui::CheckButton *)0;

gnui::Input *f_name_input=(gnui::Input *)0;

gnui::Input *f_attributes_input=(gnui::Input *)0;

gnui::Input *f_return_type_input=(gnui::Input *)0;

gnui::ReturnButton *f_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *f_panel_cancel=(gnui::Button *)0;

static void cb_static(gnui::Item*, void*) {
  f_attributes_input->value("static");
}

static void cb_virtual(gnui::Item*, void*) {
  f_attributes_input->value("virtual");
}

static void cb_const(gnui::Item*, void*) {
  f_attributes_input->value("const");
}

static void cb_inline(gnui::Item*, void*) {
  f_attributes_input->value("inline");
}

static void cb_export(gnui::Item*, void*) {
  f_attributes_input->value("export");
}

static void cb___declspec(gnui::Item*, void*) {
  f_attributes_input->value("__declspec(dllexport)");
}

static void cb___declspec1(gnui::Item*, void*) {
  f_attributes_input->value("__declspec(dllimport)");
}

static void cb___stdcall(gnui::Item*, void*) {
  f_attributes_input->value("__stdcall");
}

static void cb_Set(gnui::Button*, void*) {
  f_name_input->value("");
  f_attributes_input->value("");
  f_return_type_input->value("");
  f_public_button->value(1);
  f_c_button->value(0);
}

gnui::Window* make_function_panel() {
  gnui::Window* w;
   {gnui::Window* o = function_panel = new gnui::Window(400, 208, "function/method");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::CheckButton* o = f_public_button = new gnui::CheckButton(13, 8, 95, 25, "public");
      o->when(gnui::WHEN_NEVER);
    }
    f_c_button = new gnui::CheckButton(129, 8, 133, 25, "C declaration");
     {gnui::Input* o = f_name_input = new gnui::Input(13, 55, 237, 22, "Name(args): (blank for main())");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = f_attributes_input = new gnui::Input(13, 99, 237, 22, "Attributes (virtual, static, __declspec, ...)");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = f_return_type_input = new gnui::Input(13, 143, 377, 22, "Return Type: (blank to return outermost widget)");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::ReturnButton* o = f_panel_ok = new gnui::ReturnButton(220, 176, 80, 22, "OK");
      o->box(gnui::UP_BOX);
      o->shortcut(0xff0d);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = f_panel_cancel = new gnui::Button(310, 176, 80, 22, "Cancel");
      o->box(gnui::UP_BOX);
      o->buttonbox(gnui::NO_BOX);
      o->shortcut(0xff1b);
    }
     {gnui::Choice* o = new gnui::Choice(280, 99, 110, 22, "attr:");
      o->begin();
       {gnui::Item* o = new gnui::Item("static");
        o->callback((gnui::Callback*)cb_static);
      }
       {gnui::Item* o = new gnui::Item("virtual");
        o->callback((gnui::Callback*)cb_virtual);
      }
       {gnui::Item* o = new gnui::Item("const");
        o->callback((gnui::Callback*)cb_const);
      }
       {gnui::Item* o = new gnui::Item("inline");
        o->buttonbox(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)cb_inline);
      }
       {gnui::Item* o = new gnui::Item("export");
        o->buttonbox(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)cb_export);
      }
       {gnui::Item* o = new gnui::Item("__declspec(dllexport)");
        o->set_vertical();
        o->buttonbox(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)cb___declspec);
      }
       {gnui::Item* o = new gnui::Item("__declspec(dllimport)");
        o->set_vertical();
        o->buttonbox(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)cb___declspec1);
      }
       {gnui::Item* o = new gnui::Item("__stdcall");
        o->set_vertical();
        o->buttonbox(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)cb___stdcall);
      }
      o->end();
    }
     {gnui::Button* o = new gnui::Button(280, 55, 110, 22, "Set main()");
      o->box(gnui::UP_BOX);
      o->buttonbox(gnui::DOWN_BOX);
      o->callback((gnui::Callback*)cb_Set);
    }
    o->end();
    o->set_modal();
    o->resizable(o);
  }
  return  w;
}

gnui::Window *code_panel=(gnui::Window *)0;

static void cb_code_panel(gnui::Window* o, void*) {
  o->resizable(code_input);
}

CodeEditor *code_input=(CodeEditor *)0;

gnui::ReturnButton *code_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *code_panel_cancel=(gnui::Button *)0;

gnui::Window* make_code_panel() {
  gnui::Window* w;
   {gnui::Window* o = code_panel = new gnui::Window(290, 175, "code");
    w = o;
    o->shortcut(0xff1b);
    o->callback((gnui::Callback*)cb_code_panel);
    o->begin();
     {CodeEditor* o = code_input = new CodeEditor(6, 5, 280, 138);
      o->type(4);
      o->align(gnui::ALIGN_CENTER);
      o->when(gnui::WHEN_NEVER);
      gnui::Group::current()->resizable(o);
    }
     {gnui::Group* o = new gnui::Group(6, 148, 279, 22);
      o->begin();
       {gnui::InvisibleBox* o = new gnui::InvisibleBox(0, 0, 99, 22);
        gnui::Group::current()->resizable(o);
      }
       {gnui::ReturnButton* o = code_panel_ok = new gnui::ReturnButton(109, 0, 80, 22, "OK");
        o->shortcut(0xff0d);
        ((gnui::Window*)(o->parent()->parent()))->hotspot(o);
      }
       {gnui::Button* o = code_panel_cancel = new gnui::Button(199, 0, 80, 22, "Cancel");
        o->shortcut(0xff1b);
      }
      o->end();
    }
    o->end();
    o->set_modal();
  }
  return  w;
}

gnui::Window *codeblock_panel=(gnui::Window *)0;

gnui::Input *code_before_input=(gnui::Input *)0;

gnui::Input *code_after_input=(gnui::Input *)0;

gnui::ReturnButton *codeblock_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *codeblock_panel_cancel=(gnui::Button *)0;

gnui::Window* make_codeblock_panel() {
  gnui::Window* w;
   {gnui::Window* o = codeblock_panel = new gnui::Window(290, 131, "codeblock");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::Input* o = code_before_input = new gnui::Input(10, 22, 270, 22, "Conditional code block");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = code_after_input = new gnui::Input(10, 65, 270, 23, "\"{...child code...}\" is inserted here");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::ReturnButton* o = codeblock_panel_ok = new gnui::ReturnButton(110, 99, 80, 22, "OK");
      o->shortcut(0xff0d);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = codeblock_panel_cancel = new gnui::Button(200, 99, 80, 22, "Cancel");
      o->shortcut(0xff1b);
    }
    o->end();
    o->set_modal();
    o->resizable(o);
  }
  return  w;
}

gnui::Window *declblock_panel=(gnui::Window *)0;

gnui::Input *decl_before_input=(gnui::Input *)0;

gnui::Input *decl_after_input=(gnui::Input *)0;

gnui::ReturnButton *declblock_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *declblock_panel_cancel=(gnui::Button *)0;

gnui::Window* make_declblock_panel() {
  gnui::Window* w;
   {gnui::Window* o = declblock_panel = new gnui::Window(290, 131, "declaration block");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::Input* o = decl_before_input = new gnui::Input(10, 22, 270, 22, "Block start");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = decl_after_input = new gnui::Input(10, 66, 270, 22, "\"\\n...child code...\\n\" is inserted here");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::ReturnButton* o = declblock_panel_ok = new gnui::ReturnButton(110, 99, 80, 22, "OK");
      o->shortcut(0xff0d);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = declblock_panel_cancel = new gnui::Button(200, 99, 80, 22, "Cancel");
      o->shortcut(0xff1b);
    }
    o->end();
    o->set_modal();
    o->resizable(o);
  }
  return  w;
}

gnui::Window *decl_panel=(gnui::Window *)0;

gnui::CheckButton *decl_public_button=(gnui::CheckButton *)0;

gnui::Input *decl_input=(gnui::Input *)0;

gnui::ReturnButton *decl_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *decl_panel_cancel=(gnui::Button *)0;

gnui::Window* make_decl_panel() {
  gnui::Window* w;
   {gnui::Window* o = decl_panel = new gnui::Window(290, 175, "declaration");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::CheckButton* o = decl_public_button = new gnui::CheckButton(10, 11, 65, 22, "public");
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = decl_input = new gnui::Input(10, 44, 270, 22, "can be any declartion, like \"int x;\",\nan external symbol like \"extern int\
 foo();\",\na #directive like \"#include <foo.h>\",\nor a comment like \"//foo\
\" or \"/*foo*/\"");
      o->align(gnui::ALIGN_BOTTOM|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::ReturnButton* o = decl_panel_ok = new gnui::ReturnButton(110, 143, 80, 22, "OK");
      o->shortcut(0xff0d);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = decl_panel_cancel = new gnui::Button(200, 143, 80, 22, "Cancel");
      o->shortcut(0xff1b);
    }
    o->end();
    o->resizable(o);
  }
  return  w;
}

gnui::Window *class_panel=(gnui::Window *)0;

gnui::CheckButton *c_public_button=(gnui::CheckButton *)0;

gnui::Input *c_name_input=(gnui::Input *)0;

gnui::Input *c_subclass_input=(gnui::Input *)0;

gnui::ReturnButton *c_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *c_panel_cancel=(gnui::Button *)0;

gnui::Window* make_class_panel() {
  gnui::Window* w;
   {gnui::Window* o = class_panel = new gnui::Window(280, 164, "class");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::CheckButton* o = c_public_button = new gnui::CheckButton(10, 11, 65, 22, "public");
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = c_name_input = new gnui::Input(10, 44, 260, 22, "name:");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::Input* o = c_subclass_input = new gnui::Input(10, 89, 260, 21, "subclass of (text between : and {)");
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::ReturnButton* o = c_panel_ok = new gnui::ReturnButton(100, 132, 80, 22, "OK");
      o->shortcut(0xff0d);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = c_panel_cancel = new gnui::Button(190, 132, 80, 22, "Cancel");
      o->shortcut(0xff1b);
    }
    o->end();
    o->set_modal();
    o->resizable(o);
  }
  return  w;
}

gnui::Window *namespace_panel=(gnui::Window *)0;

gnui::Input *namespace_input=(gnui::Input *)0;

gnui::ReturnButton *namespace_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *namespace_panel_cancel=(gnui::Button *)0;

gnui::Window* make_namespace_panel() {
  gnui::Window* w;
   {gnui::Window* o = namespace_panel = new gnui::Window(300, 120, "namespace");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::Input* o = namespace_input = new gnui::Input(10, 21, 281, 20, "default is  \"gnui\", can be declared at the root or  imbricated into another\
 namespace");
      o->align(gnui::ALIGN_BOTTOM|gnui::ALIGN_LEFT|gnui::ALIGN_WRAP);
      o->when(gnui::WHEN_NEVER);
    }
     {gnui::ReturnButton* o = namespace_panel_ok = new gnui::ReturnButton(120, 92, 80, 20, "OK");
      o->shortcut(0xff0d);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = namespace_panel_cancel = new gnui::Button(210, 92, 80, 20, "Cancel");
      o->shortcut(0xff1b);
    }
    o->end();
    o->resizable(o);
  }
  return  w;
}

gnui::DoubleBufferWindow *comment_panel=(gnui::DoubleBufferWindow *)0;

static void cb_comment_panel(gnui::DoubleBufferWindow* o, void*) {
  o->hide();
}

gnui::MultiLineInput *comment_input=(gnui::MultiLineInput *)0;

gnui::ReturnButton *comment_panel_ok=(gnui::ReturnButton *)0;

gnui::Button *comment_panel_cancel=(gnui::Button *)0;

static void cb_comment_panel_cancel(gnui::Button*, void*) {
  comment_panel->hide();
}

gnui::LightButton *comment_in_source=(gnui::LightButton *)0;

gnui::LightButton *comment_in_header=(gnui::LightButton *)0;

gnui::PopupMenu *comment_predefined=(gnui::PopupMenu *)0;

gnui::Button *comment_load=(gnui::Button *)0;

gnui::DoubleBufferWindow* make_comment_panel() {
  gnui::DoubleBufferWindow* w;
   {gnui::DoubleBufferWindow* o = comment_panel = new gnui::DoubleBufferWindow(550, 318, "Comment Properties");
    w = o;
    o->type(241);
    o->labelsize(11);
    o->shortcut(0xff1b);
    o->callback((gnui::Callback*)cb_comment_panel);
    o->begin();
     {gnui::MultiLineInput* o = comment_input = new gnui::MultiLineInput(110, 10, 430, 265, "input");
      o->type(4);
      o->align(gnui::ALIGN_BOTTOM|gnui::ALIGN_LEFT);
      o->when(gnui::WHEN_NEVER);
      o->when(gnui::WHEN_ENTER_KEY_CHANGED|gnui::WHEN_RELEASE);
    }
     {gnui::Group* o = new gnui::Group(0, -1, 550, 318);
      o->labelsize(11);
      o->begin();
       {gnui::ReturnButton* o = comment_panel_ok = new gnui::ReturnButton(371, 286, 80, 21, "OK");
        o->shortcut(0xff0d);
        ((gnui::Window*)(o->parent()->parent()))->hotspot(o);
      }
       {gnui::Button* o = comment_panel_cancel = new gnui::Button(460, 286, 79, 21, "Cancel");
        o->shortcut(0xff1b);
        o->callback((gnui::Callback*)cb_comment_panel_cancel);
      }
       {gnui::InvisibleBox* o = new gnui::InvisibleBox(110, 285, 244, 21);
        o->labelsize(11);
        gnui::Group::current()->resizable(o);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(7, 10, 103, 291);
      o->set_vertical();
      o->labelsize(11);
      o->begin();
       {gnui::LightButton* o = comment_in_source = new gnui::LightButton(0, 10, 90, 20, "In Source");
        o->labelsize(11);
        o->when(gnui::WHEN_NEVER);
        o->tooltip("Put the comment into the source (.cxx) file.");
      }
       {gnui::LightButton* o = comment_in_header = new gnui::LightButton(0, 40, 90, 20, "In Header");
        o->labelsize(11);
        o->when(gnui::WHEN_NEVER);
        o->tooltip("Put the comment into the header (.h) file.");
      }
       {gnui::PopupMenu* o = comment_predefined = new gnui::PopupMenu(0, 69, 90, 20, "Predefined");
        o->labelsize(11);
        o->textsize(11);
      }
       {gnui::Button* o = comment_load = new gnui::Button(0, 100, 90, 20, "Import...");
        o->labelsize(11);
      }
       {gnui::InvisibleBox* o = new gnui::InvisibleBox(0, 132, 93, 131);
        o->set_vertical();
        o->labelsize(11);
        gnui::Group::current()->resizable(o);
      }
      o->end();
      gnui::Group::current()->resizable(o);
    }
    o->end();
    o->size_range(320, 180);
    o->set_modal();
  }
  return  w;
}

gnui::DoubleBufferWindow *sourceview_panel=(gnui::DoubleBufferWindow *)0;

gnui::TabGroup *sv_tab=(gnui::TabGroup *)0;

CodeViewer *sv_source=(CodeViewer *)0;

CodeViewer *sv_header=(CodeViewer *)0;

gnui::LightButton *sv_autorefresh=(gnui::LightButton *)0;

gnui::LightButton *sv_autoposition=(gnui::LightButton *)0;

gnui::DoubleBufferWindow* make_sourceview() {
  gnui::DoubleBufferWindow* w;
   {gnui::DoubleBufferWindow* o = sourceview_panel = new gnui::DoubleBufferWindow(520, 483, "Code View");
    w = o;
    o->type(241);
    o->shortcut(0xff1b);
    o->callback((gnui::Callback*)toggle_sourceview_cb);
    o->begin();
     {gnui::TabGroup* o = sv_tab = new gnui::TabGroup(10, 10, 500, 433);
      o->selection_color((gnui::Color)4);
      o->labelcolor((gnui::Color)7);
      o->callback((gnui::Callback*)update_sourceview_position_cb);
      o->begin();
       {gnui::Group* o = new gnui::Group(0, 25, 500, 408, "Source");
        o->hide();
        o->begin();
         {CodeViewer* o = sv_source = new CodeViewer(10, 15, 480, 383);
          o->textfont(gnui::COURIER);
          o->textsize(11);
          gnui::Group::current()->resizable(o);
        }
        o->end();
        gnui::Group::current()->resizable(o);
      }
       {gnui::Group* o = new gnui::Group(0, 25, 500, 408, "Header");
        o->begin();
         {CodeViewer* o = sv_header = new CodeViewer(10, 15, 480, 383);
          o->textfont(gnui::COURIER);
          o->textsize(11);
          gnui::Group::current()->resizable(o);
        }
        o->end();
      }
      o->end();
      gnui::Group::current()->resizable(o);
    }
     {gnui::Group* o = new gnui::Group(10, 453, 500, 20);
      o->begin();
       {gnui::Button* o = new gnui::Button(0, 0, 61, 20, "Refresh");
        o->labelsize(11);
        o->callback((gnui::Callback*)update_sourceview_cb);
      }
       {gnui::LightButton* o = sv_autorefresh = new gnui::LightButton(66, 0, 91, 20, "Auto-Refresh");
        o->labelsize(11);
        o->callback((gnui::Callback*)update_sourceview_cb);
      }
       {gnui::LightButton* o = sv_autoposition = new gnui::LightButton(162, 0, 89, 20, "Auto-Position");
        o->labelsize(11);
      }
       {gnui::Button* o = new gnui::Button(450, 0, 50, 20, "Close");
        o->labelsize(11);
        o->callback((gnui::Callback*)toggle_sourceview_b_cb);
      }
       {gnui::InvisibleBox* o = new gnui::InvisibleBox(255, 0, 190, 20);
        gnui::Group::current()->resizable(o);
      }
      o->end();
    }
    o->end();
  }
  return  w;
}
