// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#ifndef function_panel_h
#define function_panel_h
#include <gnui/Window.h>
extern gnui::Window* function_panel;
#include <gnui/CheckButton.h>
extern gnui::CheckButton* f_public_button;
extern gnui::CheckButton* f_c_button;
#include <gnui/Input.h>
extern gnui::Input* f_name_input;
extern gnui::Input* f_attributes_input;
extern gnui::Input* f_return_type_input;
#include <gnui/ReturnButton.h>
extern gnui::ReturnButton* f_panel_ok;
#include <gnui/Button.h>
extern gnui::Button* f_panel_cancel;
#include <gnui/Choice.h>
#include <gnui/Item.h>
gnui::Window* make_function_panel();
extern gnui::Window* code_panel;
#include "CodeEditor.h"
extern CodeEditor* code_input;
#include <gnui/Group.h>
#include <gnui/InvisibleBox.h>
extern gnui::ReturnButton* code_panel_ok;
extern gnui::Button* code_panel_cancel;
gnui::Window* make_code_panel();
extern gnui::Window* codeblock_panel;
extern gnui::Input* code_before_input;
extern gnui::Input* code_after_input;
extern gnui::ReturnButton* codeblock_panel_ok;
extern gnui::Button* codeblock_panel_cancel;
gnui::Window* make_codeblock_panel();
extern gnui::Window* declblock_panel;
extern gnui::Input* decl_before_input;
extern gnui::Input* decl_after_input;
extern gnui::ReturnButton* declblock_panel_ok;
extern gnui::Button* declblock_panel_cancel;
gnui::Window* make_declblock_panel();
extern gnui::Window* decl_panel;
extern gnui::CheckButton* decl_public_button;
extern gnui::Input* decl_input;
extern gnui::ReturnButton* decl_panel_ok;
extern gnui::Button* decl_panel_cancel;
gnui::Window* make_decl_panel();
extern gnui::Window* class_panel;
extern gnui::CheckButton* c_public_button;
extern gnui::Input* c_name_input;
extern gnui::Input* c_subclass_input;
extern gnui::ReturnButton* c_panel_ok;
extern gnui::Button* c_panel_cancel;
gnui::Window* make_class_panel();
extern gnui::Window* namespace_panel;
extern gnui::Input* namespace_input;
extern gnui::ReturnButton* namespace_panel_ok;
extern gnui::Button* namespace_panel_cancel;
gnui::Window* make_namespace_panel();
#include <gnui/DoubleBufferWindow.h>
extern gnui::DoubleBufferWindow* comment_panel;
#include <gnui/MultiLineInput.h>
extern gnui::MultiLineInput* comment_input;
extern gnui::ReturnButton* comment_panel_ok;
extern gnui::Button* comment_panel_cancel;
#include <gnui/LightButton.h>
extern gnui::LightButton* comment_in_source;
extern gnui::LightButton* comment_in_header;
#include <gnui/PopupMenu.h>
extern gnui::PopupMenu* comment_predefined;
extern gnui::Button* comment_load;
gnui::DoubleBufferWindow* make_comment_panel();
extern void toggle_sourceview_cb(gnui::DoubleBufferWindow*, void*);
extern gnui::DoubleBufferWindow* sourceview_panel;
#include <gnui/TabGroup.h>
extern void update_sourceview_position_cb(gnui::TabGroup*, void*);
extern gnui::TabGroup* sv_tab;
extern CodeViewer* sv_source;
extern CodeViewer* sv_header;
extern void update_sourceview_cb(gnui::Button*, void*);
extern gnui::LightButton* sv_autorefresh;
extern gnui::LightButton* sv_autoposition;
extern void toggle_sourceview_b_cb(gnui::Button*, void*);
gnui::DoubleBufferWindow* make_sourceview();
#endif
