// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#include "image_file_panel.h"

gnui::Window *images_dir_window=(gnui::Window *)0;

static void cb_images_dir_window(gnui::Window*, void*) {
  images_dir_window->hide();
  modal=0;
}

gnui::Input *images_dir_input=(gnui::Input *)0;

static void cb_Browse(gnui::Button*, void*) {
  browse_dir_cb();
}

static void cb_OK(gnui::ReturnButton*, void*) {
  images_dir_window->hide();
  modal=0;
}

static void cb_Cancel(gnui::Button*, void*) {
  images_dir_window->hide();
  modal=0; cancel=1;
}

gnui::Window* make_images_dir_window() {
  gnui::Window* w;
   {gnui::Window* o = images_dir_window = new gnui::Window(310, 98, "Images root directory");
    w = o;
    o->callback((gnui::Callback*)cb_images_dir_window);
    o->begin();
     {gnui::Input* o = images_dir_input = new gnui::Input(10, 22, 220, 22);
      ((gnui::Window*)(o->parent()))->hotspot(o);
    }
     {gnui::Button* o = new gnui::Button(230, 22, 70, 22, "Browse ...");
      o->callback((gnui::Callback*)cb_Browse);
    }
     {gnui::Widget* o = new gnui::Widget(10, 44, 220, 16, "(relative to the location of the .fl file)");
      o->box(gnui::NO_BOX);
      o->labelsize(10);
      o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE|gnui::ALIGN_WRAP);
    }
     {gnui::ReturnButton* o = new gnui::ReturnButton(150, 66, 70, 22, "OK");
      o->shortcut(0xff0d);
      o->callback((gnui::Callback*)cb_OK);
    }
     {gnui::Button* o = new gnui::Button(230, 66, 70, 22, "Cancel");
      o->callback((gnui::Callback*)cb_Cancel);
    }
    o->end();
    o->resizable(o);
  }
  return  w;
}
