// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#ifndef image_file_panel_h
#define image_file_panel_h
#include <gnui/Window.h>
extern gnui::Window* images_dir_window;
#include <gnui/Input.h>
extern gnui::Input* images_dir_input;
#include <gnui/Button.h>
#include <gnui/Widget.h>
#include <gnui/ReturnButton.h>
gnui::Window* make_images_dir_window();
#endif
