// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#ifndef template_panel_h
#define template_panel_h
// Header for //\n// "$Id$"\n//\n// FLUID template support for ...
#include <gnui/DoubleBufferWindow.h>
extern gnui::DoubleBufferWindow* template_panel;
#include <gnui/Browser.h>
extern void template_browser_cb(gnui::Browser*, void*);
extern gnui::Browser* template_browser;
#include <gnui/InvisibleBox.h>
extern gnui::InvisibleBox* template_preview;
#include <gnui/Input.h>
extern gnui::Input* template_name;
extern gnui::Input* template_instance;
#include <gnui/Group.h>
#include <gnui/Button.h>
extern void template_delete_cb(gnui::Button*, void*);
extern gnui::Button* template_delete;
#include <gnui/ReturnButton.h>
extern gnui::ReturnButton* template_submit;
gnui::DoubleBufferWindow* make_template_panel();
void template_clear();
void template_load();
// Header for //\n// End of "$Id$".\n//
#endif
