// generated by Fast Light User Interface Designer (gnuid) version 2.1000

#include "widget_panel.h"
#include <gnui/xpmImage.h>
#include "FluidType.h"
#include "gnuid_img.h"
#include "undo.h"

gnui::Window *widgetbin_panel=(gnui::Window *)0;

gnui::Window* make_widgetbin() {
  gnui::Window* w;
   {gnui::Window* o = widgetbin_panel = new gnui::Window(520, 85, "Widget Bin");
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {gnui::Group* o = new gnui::Group(3, 3, 79, 79);
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("Function"));
        o->tooltip("Function");
        o->image(gnuid_pixmap[7]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("class"));
        o->tooltip("Class");
        o->image(gnuid_pixmap[12]);
      }
       {gnui::Button* o = new gnui::Button(52, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("comment"));
        o->tooltip("Comment");
        o->image(gnuid_pixmap[46]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("code"));
        o->tooltip("Code");
        o->image(gnuid_pixmap[8]);
      }
       {gnui::Button* o = new gnui::Button(27, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("codeblock"));
        o->tooltip("Code Block");
        o->image(gnuid_pixmap[9]);
      }
       {gnui::Button* o = new gnui::Button(52, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("namespace"));
        o->tooltip("Namespace");
        o->image(gnuid_pixmap[49]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("decl"));
        o->tooltip("Declaration");
        o->image(gnuid_pixmap[10]);
      }
       {gnui::Button* o = new gnui::Button(27, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("declblock"));
        o->tooltip("Declaration Block");
        o->image(gnuid_pixmap[11]);
      }
       {gnui::Button* o = new gnui::Button(52, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("WidgetClass"));
        o->tooltip("Namespace");
        o->image(gnuid_pixmap[48]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(83, 3, 79, 79);
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Window"));
        o->tooltip("Window");
        o->image(gnuid_pixmap[1]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Group"));
        o->tooltip("Group");
        o->image(gnuid_pixmap[6]);
      }
       {gnui::Button* o = new gnui::Button(52, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::PackedGroup"));
        o->tooltip("Pack");
        o->image(gnuid_pixmap[22]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::TabGroup"));
        o->tooltip("Tabs");
        o->image(gnuid_pixmap[13]);
      }
       {gnui::Button* o = new gnui::Button(27, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ScrollGroup"));
        o->tooltip("Scroll");
        o->image(gnuid_pixmap[19]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::TiledGroup"));
        o->tooltip("Tile");
        o->image(gnuid_pixmap[20]);
      }
       {gnui::Button* o = new gnui::Button(27, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::WizardGroup"));
        o->tooltip("Wizard");
        o->image(gnuid_pixmap[21]);
      }
       {gnui::Button* o = new gnui::Button(52, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::StatusBarGroup"));
        o->tooltip("StatusBarGroup");
        o->image(gnuid_pixmap[5]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(163, 3, 54, 79);
      o->set_vertical();
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Button"));
        o->tooltip("Button");
        o->image(gnuid_pixmap[2]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ReturnButton"));
        o->tooltip("Return Button");
        o->image(gnuid_pixmap[23]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::LightButton"));
        o->tooltip("Light Button");
        o->image(gnuid_pixmap[24]);
      }
       {gnui::Button* o = new gnui::Button(27, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::RepeatButton"));
        o->tooltip("Repeat Button");
        o->image(gnuid_pixmap[25]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::CheckButton"));
        o->tooltip("Check Button");
        o->image(gnuid_pixmap[3]);
      }
       {gnui::Button* o = new gnui::Button(27, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::RadioButton"));
        o->tooltip("Round Button");
        o->image(gnuid_pixmap[4]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(218, 3, 104, 79);
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Slider"));
        o->tooltip("Slider");
        o->image(gnuid_pixmap[37]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Scrollbar"));
        o->tooltip("Scroll Bar");
        o->image(gnuid_pixmap[38]);
      }
       {gnui::Button* o = new gnui::Button(52, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ValueSlider"));
        o->tooltip("Value Slider");
        o->image(gnuid_pixmap[39]);
      }
       {gnui::Button* o = new gnui::Button(77, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ValueOutput"));
        o->tooltip("Value Output");
        o->image(gnuid_pixmap[45]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Adjuster"));
        o->tooltip("Adjuster");
        o->image(gnuid_pixmap[40]);
      }
       {gnui::Button* o = new gnui::Button(27, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ValueInput"));
        o->tooltip("Counter");
        o->image(gnuid_pixmap[41]);
      }
       {gnui::Button* o = new gnui::Button(52, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Dial"));
        o->tooltip("Dial");
        o->image(gnuid_pixmap[42]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ThumbWheel"));
        o->tooltip("ThumbWheel");
        o->image(gnuid_pixmap[43]);
      }
       {gnui::Button* o = new gnui::Button(27, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ValueInput"));
        o->tooltip("Spinner");
        o->image(gnuid_pixmap[47]);
      }
       {gnui::Button* o = new gnui::Button(52, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ValueInput"));
        o->tooltip("Value Input");
        o->image(gnuid_pixmap[44]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(323, 3, 54, 79);
      o->set_vertical();
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Input"));
        o->tooltip("Input");
        o->image(gnuid_pixmap[14]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Output"));
        o->tooltip("Output");
        o->image(gnuid_pixmap[27]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::TextEditor"));
        o->tooltip("Text Edit");
        o->image(gnuid_pixmap[29]);
      }
       {gnui::Button* o = new gnui::Button(27, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::TextDisplay"));
        o->tooltip("Text Display");
        o->image(gnuid_pixmap[28]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::FileInput"));
        o->tooltip("File Input");
        o->image(gnuid_pixmap[30]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(378, 3, 54, 79);
      o->set_vertical();
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::MenuBar"));
        o->tooltip("Menu Bar");
        o->image(gnuid_pixmap[17]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::InputBrowser"));
        o->tooltip("Input Browser");
        o->image(gnuid_pixmap[15]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::PopupMenu"));
        o->tooltip("Menu Button");
        o->image(gnuid_pixmap[26]);
      }
       {gnui::Button* o = new gnui::Button(27, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Item"));
        o->tooltip("Menu Item");
        o->image(gnuid_pixmap[16]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Choice"));
        o->tooltip("Choice");
        o->image(gnuid_pixmap[15]);
      }
       {gnui::Button* o = new gnui::Button(27, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ItemGroup"));
        o->tooltip("Sub Menu");
        o->image(gnuid_pixmap[18]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(433, 3, 29, 79);
      o->set_vertical();
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Browser"));
        o->tooltip("Browser");
        o->image(gnuid_pixmap[31]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::CheckBrowser"));
        o->tooltip("Check Browser");
        o->image(gnuid_pixmap[32]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::FileBrowser"));
        o->tooltip("File Browser");
        o->image(gnuid_pixmap[33]);
      }
      o->end();
    }
     {gnui::Group* o = new gnui::Group(463, 3, 54, 79);
      o->set_vertical();
      o->box(gnui::THIN_DOWN_BOX);
      o->begin();
       {gnui::Button* o = new gnui::Button(2, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::InvisibleBox"));
        o->tooltip("Box");
        o->image(gnuid_pixmap[5]);
      }
       {gnui::Button* o = new gnui::Button(27, 2, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::Clock"));
        o->tooltip("Clock");
        o->image(gnuid_pixmap[34]);
      }
       {gnui::Button* o = new gnui::Button(2, 27, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::HelpView"));
        o->tooltip("Help View");
        o->image(gnuid_pixmap[35]);
      }
       {gnui::Button* o = new gnui::Button(2, 52, 25, 25);
        o->box(gnui::THIN_UP_BOX);
        o->callback((gnui::Callback*)type_make_cb, (void*)("gnui::ProgressBar"));
        o->tooltip("Progress");
        o->image(gnuid_pixmap[36]);
      }
      o->end();
    }
    o->end();
    o->set_non_modal();
    o->resizable(o);
  }
  return  w;
}

void type_make_cb(gnui::Widget*w,void*d) {
  FluidType *t = FluidType::make((char*)d);
    if (t) {
      Undo::checkpoint();
      select_only(t);
      modflag = 1;
      t->open();
    }
}

gnui::TabGroup *panel_tabs=(gnui::TabGroup *)0;

gnui::Group *gInput=(gnui::Group *)0;

static gnui::Input *i_class_name=(gnui::Input *)0;

static gnui::Choice *m_subtype=(gnui::Choice *)0;

static gnui::Input *i_label=(gnui::Input *)0;

gnui::Group *gAlignment=(gnui::Group *)0;

gnui::CheckButton *include_image_button=(gnui::CheckButton *)0;

gnui::Widget *image_label=(gnui::Widget *)0;

gnui::Button *image_button=(gnui::Button *)0;

gnui::Group *gDimensions=(gnui::Group *)0;

gnui::ValueInput *widget_x=(gnui::ValueInput *)0;

gnui::ValueInput *widget_y=(gnui::ValueInput *)0;

gnui::ValueInput *widget_w=(gnui::ValueInput *)0;

gnui::ValueInput *widget_h=(gnui::ValueInput *)0;

gnui::CheckButton *set_xy=(gnui::CheckButton *)0;

gnui::Group *gValues=(gnui::Group *)0;

gnui::Group *gAttributes=(gnui::Group *)0;

static gnui::Group *BoxColor=(gnui::Group *)0;

static gnui::Group *ButtonBox=(gnui::Group *)0;

static gnui::Group *Labels=(gnui::Group *)0;

gnui::MultiLineInput *extra_code_input=(gnui::MultiLineInput *)0;

gnui::CheckButton *overlaybutton=(gnui::CheckButton *)0;

gnui::LightButton *wLiveMode=(gnui::LightButton *)0;

gnui::Window* make_widget_panel() {
  gnui::Window* w;
   {gnui::Window* o = new gnui::Window(380, 380);
    w = o;
    o->shortcut(0xff1b);
    ((gnui::Window*)(o))->hotspot(o);
    o->begin();
     {gnui::TabGroup* o = panel_tabs = new gnui::TabGroup(0, 0, 380, 340);
      o->callback((gnui::Callback*)propagate_tabs);
      o->begin();
       {gnui::Group* o = new gnui::Group(0, 20, 380, 320, "GUI");
        o->color((gnui::Color)0x14aef700);
        o->callback((gnui::Callback*)propagate_group);
        o->hide();
        o->begin();
         {gnui::Group* o = gInput = new gnui::Group(80, 9, 290, 44);
          o->callback((gnui::Callback*)propagate_group);
          o->begin();
           {gnui::Input* o = i_class_name = new gnui::Input(0, 0, 170, 22, "Class");
            o->callback((gnui::Callback*)user_class_cb, (void*)(4));
            o->when(gnui::WHEN_CHANGED);
            o->tooltip("This allows you to name a user-defined class that this widget is an instance \
of, rather than an gnui built-in class. You will need to add a #include declar\
ation so that the definition of your class is included in the gnuid output.");
          }
           {gnui::Choice* o = m_subtype = new gnui::Choice(170, 0, 120, 22);
            o->callback((gnui::Callback*)subtype_cb);
            o->tooltip("Selects a value for type() for this widget");
          }
           {gnui::Input* o = i_label = new gnui::Input(0, 22, 290, 22, "Label");
            o->callback((gnui::Callback*)label_cb);
            o->when(gnui::WHEN_CHANGED);
            o->tooltip("Text displayed on or next to the widget");
            o->take_focus();
          }
          o->end();
        }
         {gnui::Group* o = gAlignment = new gnui::Group(80, 54, 293, 22, "Alignment");
          o->callback((gnui::Callback*)propagate_group);
          o->align(gnui::ALIGN_LEFT);
          o->begin();
           {gnui::CheckButton* o = include_image_button = new gnui::CheckButton(272, 0, 20, 22, "inline");
            o->set_vertical();
            o->callback((gnui::Callback*)image_inlined_cb);
            o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_WRAP);
            o->tooltip("The image data is inserted as inline data into the output C++ code, rather th\
an generating code to read the image file.");
          }
           {gnui::Widget* o = new gnui::Widget(1, 0, 70, 22, "Alignment");
            o->box(gnui::NO_BOX);
            o->align(gnui::ALIGN_RIGHT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
            o->hide();
          }
           {gnui::Button* o = new gnui::Button(0, 2, 20, 20, "@4->");
            o->type(gnui::Button::TOGGLE);
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_LEFT));
            o->tooltip("Places label on the left of the widget");
          }
           {gnui::Button* o = new gnui::Button(20, 2, 20, 20, "@6->");
            o->type(gnui::Button::TOGGLE);
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_RIGHT));
            o->tooltip("Places label on the right of the widget");
          }
           {gnui::Button* o = new gnui::Button(40, 2, 20, 20, "@8->");
            o->type(gnui::Button::TOGGLE);
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_TOP));
            o->tooltip("Places label on the top of the widget");
          }
           {gnui::Button* o = new gnui::Button(60, 2, 20, 20, "@2->");
            o->type(gnui::Button::TOGGLE);
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_BOTTOM));
            o->tooltip("Places label on the bottom of the widget");
          }
           {gnui::Button* o = new gnui::Button(91, 2, 40, 20, "inside");
            o->type(gnui::Button::TOGGLE);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_INSIDE));
            o->tooltip("Places label inside the widget");
          }
           {gnui::Button* o = new gnui::Button(131, 2, 40, 20, "clip");
            o->type(gnui::Button::TOGGLE);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_CLIP));
            o->tooltip("Turn on clipping to the widget's area when drawing label.  This is slower so \
it should be left off if label will fit");
          }
           {gnui::Button* o = new gnui::Button(171, 2, 40, 20, "wrap");
            o->type(gnui::Button::TOGGLE);
            o->callback((gnui::Callback*)align_cb, (void*)(gnui::ALIGN_WRAP));
            o->tooltip("Word-wrap the label");
          }
          o->end();
        }
         {gnui::Widget* o = image_label = new gnui::Widget(5, 79, 78, 22, "Image");
          o->box(gnui::NO_BOX);
          o->align(gnui::ALIGN_RIGHT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE);
        }
         {gnui::Button* o = image_button = new gnui::Button(80, 79, 290, 22);
          o->color((gnui::Color)7);
          o->callback((gnui::Callback*)image_cb, (void*)(1));
          o->align(gnui::ALIGN_LEFT|gnui::ALIGN_CENTER|gnui::ALIGN_INSIDE|gnui::ALIGN_CLIP);
          o->tooltip("Select an image to label the widget");
        }
         {gnui::Group* o = gDimensions = new gnui::Group(80, 112, 290, 23, "Dimensions");
          o->callback((gnui::Callback*)propagate_group);
          o->align(gnui::ALIGN_LEFT);
          o->begin();
           {gnui::ValueInput* o = widget_x = new gnui::ValueInput(0, 0, 55, 22, "x");
            o->labelsize(11);
            o->maximum(2000);
            o->step(1);
            o->value(10);
            o->callback((gnui::Callback*)x_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The x coordinate of the widget.");
          }
           {gnui::ValueInput* o = widget_y = new gnui::ValueInput(55, 0, 55, 22, "y");
            o->labelsize(11);
            o->maximum(2000);
            o->step(1);
            o->value(10);
            o->callback((gnui::Callback*)y_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The y coordinate of the widget.");
          }
           {gnui::ValueInput* o = widget_w = new gnui::ValueInput(110, 0, 55, 22, "w");
            o->labelsize(11);
            o->maximum(2000);
            o->step(1);
            o->value(10);
            o->callback((gnui::Callback*)width_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The width of the widget.");
          }
           {gnui::ValueInput* o = widget_h = new gnui::ValueInput(165, 0, 55, 22, "h");
            o->labelsize(11);
            o->maximum(2000);
            o->step(1);
            o->value(10);
            o->callback((gnui::Callback*)height_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The height of the widget.");
          }
           {gnui::CheckButton* o = set_xy = new gnui::CheckButton(225, 0, 25, 22, "xy");
            o->labelsize(11);
            o->callback((gnui::Callback*)set_xy_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
            o->tooltip("Window will use this x,y rather than being positioned by the operating system\
.");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(245, 0, 45, 22, "slider size");
            o->labelsize(11);
            o->callback((gnui::Callback*)slider_size_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The size of the scroller");
          }
          o->end();
        }
         {gnui::Group* o = gValues = new gnui::Group(80, 147, 290, 23, "Values");
          o->callback((gnui::Callback*)propagate_group);
          o->align(gnui::ALIGN_LEFT);
          o->begin();
           {gnui::ValueInput* o = new gnui::ValueInput(0, 0, 55, 22, "Value");
            o->callback((gnui::Callback*)value_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The initial value of this widget");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(55, 0, 55, 22, "min");
            o->labelsize(11);
            o->callback((gnui::Callback*)min_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The minimum value for this valuator");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(110, 0, 55, 23, "max");
            o->labelsize(11);
            o->callback((gnui::Callback*)max_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("The maximum value for this valuator");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(165, 0, 55, 22, "step");
            o->labelsize(11);
            o->callback((gnui::Callback*)step_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("step:\nRound all movements to multiples of this.\n");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(245, 0, 45, 22, "line");
            o->labelsize(11);
            o->minimum(1);
            o->step(1);
            o->callback((gnui::Callback*)line_cb);
            o->align(gnui::ALIGN_TOP|gnui::ALIGN_LEFT|gnui::ALIGN_CENTER);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("linesize:\nIncrement/decrement for arrow keys.");
          }
          o->end();
        }
         {gnui::Group* o = gAttributes = new gnui::Group(80, 171, 280, 44, "Attributes");
          o->callback((gnui::Callback*)propagate_group);
          o->align(gnui::ALIGN_LEFT);
          o->begin();
           {gnui::CheckButton* o = new gnui::CheckButton(0, 0, 65, 22, "Visible");
            o->callback((gnui::Callback*)visible_cb);
            o->tooltip("If unchecked the widget is initially invisible.");
          }
           {gnui::CheckButton* o = new gnui::CheckButton(65, 0, 65, 22, "Active");
            o->callback((gnui::Callback*)active_cb);
            o->tooltip("If unchecked the widget is initially inactive (disabled, grayed out).");
          }
           {gnui::CheckButton* o = new gnui::CheckButton(130, 0, 80, 22, "Resizable");
            o->callback((gnui::Callback*)resizable_cb);
            o->tooltip("If on, this widget and all its parents are resizable.  When the parent resize\
s it moves/resizes all its children so that this widget's edges remain the sam\
e distance from all four sides of the parent.  If this is off this widget will\
 not resize, unless it overlaps a resizable sibling.");
          }
           {gnui::CheckButton* o = new gnui::CheckButton(210, 0, 70, 22, "Hotspot");
            o->callback((gnui::Callback*)hotspot_cb);
            o->tooltip("Positions the window so this widget is under the mouse.  This is done when sh\
ow() is called.");
          }
           {gnui::CheckButton* o = new gnui::CheckButton(0, 20, 65, 22, "Border");
            o->callback((gnui::Callback*)border_cb);
            o->tooltip("Enable the window manager border");
          }
           {gnui::CheckButton* o = new gnui::CheckButton(65, 20, 65, 22, "Modal");
            o->callback((gnui::Callback*)modal_cb);
            o->tooltip("This window will stay on top of others in the application and will block even\
ts from going to other windows until it is hidden or closed.");
          }
           {gnui::CheckButton* o = new gnui::CheckButton(130, 20, 65, 22, "Child");
            o->callback((gnui::Callback*)non_modal_cb);
            o->tooltip("This window will stay on top of others in the application.");
          }
          o->end();
        }
         {gnui::InvisibleBox* o = new gnui::InvisibleBox(25, 215, 55, 25, "Shortcut");
          o->align(gnui::ALIGN_RIGHT|gnui::ALIGN_INSIDE);
        }
         {Shortcut_Button* o = new Shortcut_Button(80, 216, 290, 22);
          o->color((gnui::Color)7);
          o->callback((gnui::Callback*)shortcut_in_cb);
          o->align(gnui::ALIGN_LEFT|gnui::ALIGN_INSIDE);
          o->tooltip("To set a shortcut:\n   Click here, then type the key combination you want.\nT\
o delete the shortcut:\n   Click here, then type backspace.\nTo get out of sho\
rtcut-setting mode:\n   Click the mouse on this again, or on some other field.");
        }
         {gnui::WordwrapInput* o = new gnui::WordwrapInput(80, 240, 290, 70, "Tooltip");
          o->type(5);
          o->box(gnui::BORDER_BOX);
          o->color((gnui::Color)0xffffe100);
          o->callback((gnui::Callback*)tooltip_cb);
          gnui::Group::current()->resizable(o);
          o->tooltip("The pop up tooltip which should be used for the widget.");
        }
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 20, 380, 320, "Style");
        o->color((gnui::Color)0xd4b38d00);
        o->callback((gnui::Callback*)propagate_group);
        o->hide();
        o->begin();
         {gnui::Group* o = BoxColor = new gnui::Group(85, 9, 270, 66);
          o->callback((gnui::Callback*)propagate_group);
          o->begin();
           {gnui::Choice* o = new gnui::Choice(0, 0, 270, 22, "Box");
            o->callback((gnui::Callback*)box_cb);
            o->tooltip("Type of box to draw around the contents of the widget.");
          }
           {gnui::LightButton* o = new gnui::LightButton(0, 22, 135, 22, "Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)color_cb);
            o->tooltip("Color of the contents area.");
            o->type(0);
          }
           {gnui::LightButton* o = new gnui::LightButton(135, 22, 135, 22, "Text Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)text_color_cb);
            o->tooltip("Color of text drawn in the widget.");
            o->type(0);
          }
           {gnui::LightButton* o = new gnui::LightButton(0, 44, 135, 22, "Selection Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)selection_color_cb);
            o->tooltip("Color to draw behind selected text");
            o->type(0);
          }
           {gnui::LightButton* o = new gnui::LightButton(135, 44, 135, 22, "Selected Text Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)selected_text_color_cb);
            o->tooltip("Color to draw selected text");
            o->type(0);
          }
          o->end();
        }
         {gnui::Group* o = ButtonBox = new gnui::Group(85, 88, 270, 66);
          o->callback((gnui::Callback*)propagate_group);
          o->begin();
           {gnui::Choice* o = new gnui::Choice(0, 0, 270, 22, "Button box");
            o->callback((gnui::Callback*)button_box_cb);
            o->tooltip("Type of box to draw around buttons");
          }
           {gnui::LightButton* o = new gnui::LightButton(0, 22, 135, 22, "Button Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)button_color_cb);
            o->tooltip("Color to draw buttons inside the widget.");
            o->type(0);
          }
           {gnui::LightButton* o = new gnui::LightButton(135, 22, 135, 22, "Label Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)label_color_cb);
            o->tooltip("Color to draw the labels on buttons, and color to draw the label.");
            o->type(0);
          }
           {gnui::LightButton* o = new gnui::LightButton(0, 44, 135, 22, "Highlight Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)highlight_color_cb);
            o->tooltip("Color to use to draw buttons when they are highlighted.  Use color zero (the \
black top-left chip in the color chooser) to disable highlighting.");
            o->type(0);
          }
           {gnui::LightButton* o = new gnui::LightButton(135, 44, 135, 22, "Highlight Label Color");
            o->labelsize(11);
            o->textsize(11);
            o->callback((gnui::Callback*)highlight_label_color_cb);
            o->tooltip("Color to draw the button labels when the buttons are highlighted.  Use color \
zero (the black top-left chip in the color chooser) to leave the label colors \
unchanged.");
            o->type(0);
          }
          o->end();
        }
         {gnui::Group* o = Labels = new gnui::Group(85, 165, 270, 80);
          o->callback((gnui::Callback*)propagate_group);
          o->begin();
           {gnui::Choice* o = new gnui::Choice(0, 0, 270, 22, "Label Style");
            o->callback((gnui::Callback*)label_style_cb);
            o->tooltip("How to draw the label.");
          }
           {gnui::Choice* o = new gnui::Choice(0, 22, 215, 22, "Label Font");
            o->callback((gnui::Callback*)label_font_cb);
            o->tooltip("Font to use for the label");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(215, 22, 55, 22);
            o->maximum(100);
            o->step(0.1);
            o->value(14);
            o->callback((gnui::Callback*)label_size_cb);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("Size of the font to use for the label");
          }
           {gnui::Choice* o = new gnui::Choice(0, 55, 215, 22, "Text Font");
            o->callback((gnui::Callback*)text_font_cb);
            o->tooltip("Font to use for text displayed inside the widget");
          }
           {gnui::ValueInput* o = new gnui::ValueInput(215, 55, 55, 22);
            o->maximum(100);
            o->step(0.1);
            o->value(14);
            o->callback((gnui::Callback*)text_size_cb);
            o->when(gnui::WHEN_ENTER_KEY);
            o->tooltip("Size of the font to use for text displayed inside the widget");
          }
           {gnui::Widget* o = new gnui::Widget(0, 77, 270, 3, "resizable");
            o->align(gnui::ALIGN_BOTTOM);
            o->hide();
            o->deactivate();
          }
          o->end();
        }
         {gnui::Button* o = new gnui::Button(85, 258, 124, 22, "Reset to default");
          o->callback((gnui::Callback*)default_cb);
          o->tooltip("Reset all the above items to the default values for this widget class.");
        }
         {gnui::InvisibleBox* o = new gnui::InvisibleBox(85, 280, 270, 25);
          gnui::Group::current()->resizable(o);
        }
        o->end();
      }
       {gnui::Group* o = new gnui::Group(0, 20, 380, 320, "C++");
        o->color((gnui::Color)0x93d49c00);
        o->callback((gnui::Callback*)propagate_group);
        o->begin();
         {gnui::Input* o = new gnui::Input(80, 9, 230, 22, "Name");
          o->callback((gnui::Callback*)name_cb);
          o->when(gnui::WHEN_CHANGED);
          o->tooltip("The variable or member name in which to store a pointer to this widget.");
        }
         {gnui::CheckButton* o = new gnui::CheckButton(315, 9, 50, 22, "public");
          o->callback((gnui::Callback*)name_public_cb);
          o->tooltip("Make the variable public");
        }
         {gnui::MultiLineInput* o = extra_code_input = new gnui::MultiLineInput(80, 37, 285, 99, "Extra Code");
          o->type(4);
          o->textfont(gnui::COURIER);
          o->textsize(11);
          o->callback((gnui::Callback*)extra_code_input_cb, (void*)(0));
          o->tooltip("Extra code to be exectuted after the widget is created. The variable \"o\" po\
ints at the widget.");
        }
         {gnui::MultiLineInput* o = new gnui::MultiLineInput(80, 143, 285, 99, "Callback");
          o->type(4);
          o->textfont(gnui::COURIER);
          o->textsize(11);
          o->callback((gnui::Callback*)callback_cb);
          o->tooltip("The name of the callback function, or code body of the callback function");
        }
         {gnui::Widget* o = new gnui::Widget(80, 154, 165, 65, "resizable");
          o->hide();
          o->deactivate();
          gnui::Group::current()->resizable(o);
        }
         {gnui::Input* o = new gnui::Input(80, 242, 145, 22, "User Data");
          o->callback((gnui::Callback*)user_data_cb);
          o->tooltip("Value passed as the second argument to the callback.  This must be of the typ\
e given below.");
        }
         {gnui::Choice* o = new gnui::Choice(265, 242, 100, 22, "When");
          o->callback((gnui::Callback*)when_cb);
          o->when(gnui::WHEN_CHANGED);
          o->tooltip("What actions cause the callback to be called.");
        }
         {gnui::Input* o = new gnui::Input(80, 264, 145, 22, "Type");
          o->callback((gnui::Callback*)user_data_type_cb);
          o->tooltip("Type of User Data. This must be \"long\" or a pointer.");
        }
        o->end();
        gnui::Group::current()->resizable(o);
      }
      o->end();
      gnui::Group::current()->resizable(o);
    }
     {gnui::Group* o = new gnui::Group(0, 350, 380, 24);
      o->begin();
       {gnui::CheckButton* o = overlaybutton = new gnui::CheckButton(20, 0, 120, 24, "&Overlays");
        o->callback((gnui::Callback*)overlay_cb);
        gnui::Group::current()->resizable(o);
        o->tooltip("Turns the overlays (red outlines) off so you can see the edges better.");
        o->value(!overlays_invisible);
      }
       {gnui::ReturnButton* o = new gnui::ReturnButton(235, 1, 65, 23, "OK");
        o->shortcut(0xff0d);
        o->callback((gnui::Callback*)ok_cb);
        o->tooltip("Closes this attribute window");
      }
       {gnui::Button* o = new gnui::Button(310, 1, 65, 23, "Cancel");
        o->callback((gnui::Callback*)cancel_cb);
        o->tooltip("Sorry, cancel does not really work yet.");
      }
       {gnui::LightButton* o = wLiveMode = new gnui::LightButton(95, 2, 90, 22, "LiveMode!");
        o->callback((gnui::Callback*)live_mode_cb);
      }
      o->end();
    }
    o->end();
  }
  return  w;
}
